import esbuild from "esbuild";
import process from "process";
import builtInModules from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: {
    main: 'src/main.ts',
  },
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtInModules],
  format: 'cjs',
  target: 'ES6',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outdir: './dist',
undefined
});

await context.rebuild();

// Copy manifest.json to dist
const manifestSrc = 'manifest.json';
const manifestDst = path.join('dist', 'manifest.json');
fs.copyFileSync(manifestSrc, manifestDst);
console.log(`✓ Copied ${manifestSrc} to ${manifestDst}`);

if (prod) {
  process.exit(0);
} else {
  await context.watch();
}
