import { defineConfig } from 'vite';
import { resolve } from 'path';
import builtInModules from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(({ mode }) => {
  const prod = mode === 'production';

  return {
    build: {
      lib: {
        entry: resolve('src/main.ts'),
        name: 'main',
        fileName: () => 'main.js',
        formats: ['cjs'],
      },
      minify: prod,
      sourcemap: prod ? false : 'inline',
      cssCodeSplit: false,
      emptyOutDir: false,
      outDir: 'dist',
      rollupOptions: {
        input: {
          main: resolve('src/main.ts'),
        },
        output: {
          banner,
          entryFileNames: 'main.js',
          assetFileNames: 'styles.css',
          format: 'cjs',
          dir: 'dist',
        },
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
          ...builtInModules,
        ],
      },
    },
    plugins: [
      {
        name: 'copy-manifest',
        writeBundle() {
          const manifestSrc = 'manifest.json';
          const manifestDst = path.join('dist', 'manifest.json');
          fs.copyFileSync(manifestSrc, manifestDst);
          console.log(`✓ Copied ${manifestSrc} to ${manifestDst}`);
        },
      },
    ],
  };
});
