#!/usr/bin/env bash
#MISE description="Install dependencies with pnpm"

set -euo pipefail

if command -v bkt &> /dev/null; then
  bkt --ttl=24h --modtime=pnpm-lock.yaml -- pnpm install
else
  pnpm install
fi
